language: csharp
solution: KnowledgeBase.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore KnowledgeBase.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
   - xbuild /p:Configuration=Release KnowledgeBase.sln
   - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./KnowLedgeBase.Tests/bin/Release/KnowLedgeBase.Tests.dll
   - chmod a+x ./build-extension.sh
   - ./build-extension.sh
deploy:
  provider: azure_web_apps