language: csharp
solution: KnowledgeBase.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore KnowledgeBase.sln
  - nuget install xunit.runnner.console -Version 2.1.0 -OutputDirectory testrunner